apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "app.siji/v1alpha1",
          "kind": "Nginx",
          "metadata": {
            "name": "example-nginx"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: nginx-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: The Nginx CRD
      displayName: Nginx
      kind: Nginx
      name: nginxes.app.siji
      version: v1alpha1
  description: Deploy Nginx by using operator
  displayName: Nginx Operator
  install:
    spec:
      deployments:
      - name: nginx-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: nginx-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: nginx-operator
            spec:
              containers:
              - command:
                - nginx-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: nginx-operator
                image: quay.io/siji/nginx-operator:v0.0.1
                imagePullPolicy: Always
                name: nginx-operator
                resources: {}
              serviceAccountName: nginx-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - nginx-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - app.siji
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: nginx-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nginx
  maintainers:
  - email: zhiweik@gmail.com
    name: zhiwei
  maturity: alpha
  provider:
    name: zhiwei
  replaces: nginx-operator.v0.0.0
  version: 0.0.1
